radicale:
  build: "."
  ports:
    - "5232:5232"
  environment:
    UID: 33
    GUID: 33
  volumes:
    - ./shared/radicale:/etc/radicale
    - ./shared/radicale-data:/home/radicale/data
  restart: always